package net.Parkinsons.parking;

public class SimulatieStartGUI extends javax.swing.JFrame {

    /**
     * Creates new form SimulatieStartup
     */
    public SimulatieStartGUI() {
        initComponents();
        setTitle("Parkinson Initializer");
        setResizable(false);
        setVisible(true);
        rowAmount = -1;
        floorAmount = -1;
        placeAmount = -1;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        carControl = new javax.swing.JLabel();
        vehiclesPerMinute = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vehiclesPerMinute1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vehiclesPerMinute2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1Shadow = new javax.swing.JLabel();
        vehiclesPerMinute3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        garageSize = new javax.swing.JLabel();
        rowAmountLabel = new javax.swing.JLabel();
        placesAmountLabel = new javax.swing.JLabel();
        floorAmountLabel = new javax.swing.JLabel();
        startSimulation = new javax.swing.JButton();
        floorInput = new javax.swing.JTextField();
        rowsInput = new javax.swing.JTextField();
        placeInput = new javax.swing.JTextField();
        backGround = new javax.swing.JLabel();
        rowAmountLabel1 = new javax.swing.JLabel();
        rowsInput1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(260, 60, 20, 140);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        carControl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        carControl.setForeground(new java.awt.Color(153, 204, 255));
        carControl.setText("Instellingen [Werkt niet!]");
        jPanel2.add(carControl);
        carControl.setBounds(10, 0, 290, 32);

        vehiclesPerMinute.setText("300");
        vehiclesPerMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclesPerMinuteActionPerformed(evt);
            }
        });
        vehiclesPerMinute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vehiclesPerMinuteKeyTyped(evt);
            }
        });
        jPanel2.add(vehiclesPerMinute);
        vehiclesPerMinute.setBounds(200, 40, 40, 20);

        jLabel2.setForeground(new java.awt.Color(153, 204, 255));
        jLabel2.setText("Auto's per minuut (globaal)");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 40, 170, 16);

        vehiclesPerMinute1.setText("500");
        vehiclesPerMinute1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclesPerMinute1ActionPerformed(evt);
            }
        });
        vehiclesPerMinute1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vehiclesPerMinute1KeyTyped(evt);
            }
        });
        jPanel2.add(vehiclesPerMinute1);
        vehiclesPerMinute1.setBounds(200, 60, 40, 20);

        jLabel4.setForeground(new java.awt.Color(153, 204, 255));
        jLabel4.setText("Auto's per minuut (werkdagen)");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 60, 180, 16);

        vehiclesPerMinute2.setText("30");
        vehiclesPerMinute2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclesPerMinute2ActionPerformed(evt);
            }
        });
        vehiclesPerMinute2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vehiclesPerMinute2KeyTyped(evt);
            }
        });
        jPanel2.add(vehiclesPerMinute2);
        vehiclesPerMinute2.setBounds(200, 100, 40, 20);

        jLabel5.setForeground(new java.awt.Color(153, 204, 255));
        jLabel5.setText("Auto's per minuut (weekenden)");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 80, 180, 16);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 130, 210, 0);

        vehiclesPerMinute3.setText("250");
        vehiclesPerMinute3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclesPerMinute3ActionPerformed(evt);
            }
        });
        vehiclesPerMinute3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vehiclesPerMinute3KeyTyped(evt);
            }
        });
        jPanel2.add(vehiclesPerMinute3);
        vehiclesPerMinute3.setBounds(200, 80, 40, 20);

        jLabel8.setForeground(new java.awt.Color(153, 204, 255));
        jLabel8.setText("Ticks per seconde");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 100, 180, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(280, 60, 290, 170);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parkin'Sons net.Parkinsons.parking.Simulator");
        jPanel1.add(jLabel1Shadow);
        jLabel1.setBounds(-64, 10, 620, 50);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 213, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parkin'Sons net.Parkinsons.parking.Simulator");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-70, 10, 620, 50);

        garageSize.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        garageSize.setForeground(new java.awt.Color(153, 204, 255));
        garageSize.setText("Garage Formaat");
        jPanel1.add(garageSize);
        garageSize.setBounds(50, 60, 220, 32);

        rowAmountLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rowAmountLabel.setForeground(new java.awt.Color(153, 204, 255));
        rowAmountLabel.setText("Aantal rijen");
        jPanel1.add(rowAmountLabel);
        rowAmountLabel.setBounds(50, 100, 100, 19);

        placesAmountLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        placesAmountLabel.setForeground(new java.awt.Color(153, 204, 255));
        placesAmountLabel.setText("Aantal verdiepingen");
        jPanel1.add(placesAmountLabel);
        placesAmountLabel.setBounds(50, 130, 110, 19);

        floorAmountLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        floorAmountLabel.setForeground(new java.awt.Color(153, 204, 255));
        floorAmountLabel.setText("Aantal plaatsen");
        jPanel1.add(floorAmountLabel);
        floorAmountLabel.setBounds(50, 160, 160, 19);

        startSimulation.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        startSimulation.setText("Begin Simulatie");
        startSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSimulationActionPerformed(evt);
            }
        });
        jPanel1.add(startSimulation);
        startSimulation.setBounds(140, 210, 330, 50);

        floorInput.setText("3");
        floorInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                floorInputKeyTyped(evt);
            }
        });
        jPanel1.add(floorInput);
        floorInput.setBounds(200, 160, 30, 20);

        rowsInput.setText("8");
        rowsInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rowsInputKeyTyped(evt);
            }
        });
        jPanel1.add(rowsInput);
        rowsInput.setBounds(200, 100, 30, 20);

        placeInput.setText("35");
        placeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeInputActionPerformed(evt);
            }
        });
        placeInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeInputKeyTyped(evt);
            }
        });
        jPanel1.add(placeInput);
        placeInput.setBounds(200, 130, 30, 20);

        backGround.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jPanel1.add(backGround);
        backGround.setBounds(0, 0, 590, 280);

        rowAmountLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rowAmountLabel1.setForeground(new java.awt.Color(255, 255, 255));
        rowAmountLabel1.setText("Aantal rijen");
        jPanel1.add(rowAmountLabel1);
        rowAmountLabel1.setBounds(50, 100, 79, 19);

        rowsInput1.setText("0");
        rowsInput1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rowsInput1KeyTyped(evt);
            }
        });
        jPanel1.add(rowsInput1);
        rowsInput1.setBounds(200, 100, 30, 20);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(260, 60, 20, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void startSimulationActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            rowAmount = Integer.parseInt(rowsInput.getText());
            placeAmount = Integer.parseInt(placeInput.getText());
            floorAmount = Integer.parseInt(floorInput.getText());

            if (rowAmount == 0 || placeAmount == 0 || floorAmount == 0) {
                System.out.println("ERROR");
            } else {

              //create new simulator//
            }
        } catch(IllegalArgumentException e)
        {

        }
    }



    private void floorInputKeyTyped(java.awt.event.KeyEvent evt) {

        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        if (floorInput.getText().length()>=3) {
            evt.consume();
        }

    }

    private void rowsInputKeyTyped(java.awt.event.KeyEvent evt) {
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();

        }
        if (rowsInput.getText().length()>=3) {
            evt.consume();
        } else if (rowsInput.getText().length()<=3) {
        }

    }

    private void placeInputKeyTyped(java.awt.event.KeyEvent evt) {
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        if (placeInput.getText().length()>=3) {
            evt.consume();
        }
    }

    private void placeInputActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void rowsInput1KeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void vehiclesPerMinuteKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void vehiclesPerMinuteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void vehiclesPerMinute1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void vehiclesPerMinute1KeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void vehiclesPerMinute2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void vehiclesPerMinute2KeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void vehiclesPerMinute3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void vehiclesPerMinute3KeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulatieStartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulatieStartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulatieStartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatieStartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatieStartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel carControl;
    private javax.swing.JLabel floorAmountLabel;
    private javax.swing.JTextField floorInput;
    private javax.swing.JLabel garageSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField placeInput;
    private javax.swing.JLabel placesAmountLabel;
    private javax.swing.JLabel rowAmountLabel;
    private javax.swing.JLabel rowAmountLabel1;
    private javax.swing.JTextField rowsInput;
    private javax.swing.JTextField rowsInput1;
    private javax.swing.JButton startSimulation;
    private javax.swing.JTextField vehiclesPerMinute;
    private javax.swing.JTextField vehiclesPerMinute1;
    private javax.swing.JTextField vehiclesPerMinute2;
    private javax.swing.JTextField vehiclesPerMinute3;
    // End of variables declaration
    private javax.swing.JLabel jLabel1Shadow;
    public static int rowAmount;
    public static int placeAmount;
    public static int floorAmount;

}
